version: "3.9"
services:
  api:
    build: .
    image: fer-api:v1.1
    volumes:
    - .:/app
    ports:
    - "3001:3000"

  nginx:
    image: nginx
    volumes:
    - ./nginx:/etc/nginx/conf.d
    ports:
    - "80:80"