version: "3.9"
services:
  model-service:
    build:
      context: ./model_service
    image: model-service:v1.0
    ports:
      - 5000:5000
    volumes:
    - ./model_service:/app
    restart: on-failure

  app:
    build:
      context: ./app
    image: main-app:v1.0
    ports:
      - 5001:5001
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - app
      - model-service
