version: "3.9"
services:
  api:
    build: .
    image: fer-app:v1.3
    volumes:
    - .:/app
    expose:
      - "8080"
    restart: always

  nginx-proxy:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "80:80"
    depends_on:
      - api
    restart: always